### ISSUE TITLE
Unable to render props/state after the initial render

### ISSUE THREAD

**Issue by matthewchan15** [plotly/react-circosJS#4]
Hey @nicgirault ,

I've been wrapping react-circosJS into a dash component. The issue I have right now is that the component can be rendered only once. 

The reason I say this is because, it only has a ```componentDidMount()``` that allows it to be run once on start up. But, it should also contain other React methods like ```componentDidUpdate()``` so it can be rendered afterwards. I am able to render the component once, but than no props or state can be fired to the component because it simply doesn't render in the react-wrapper more than once. As a test case, I modified the source code, and was able to make callbacks fire.

If you can fix this up, or let me know how to update the props/state after the initial render that would be awesome!

**Comment by lidaof** [comment]
Hi @matthewchan15 @nicgirault,

First of all, thanks for the nice package...

I also encountered this problem that the circos plot is not re-rendering when new data is coming.
can you tell how to fix this?
Thanks.
